# Setup
title:             What has Tad accomplished with his days?
tagline:          'Tad Dallas'
description:      ''
baseurl:          /LabNotebook
paginate:         30

github:
  repo:           https://github.com/taddallas/LabNotebook
